#!/bin/sh -eu

cd ${1:-${ZEUS_ROOT:-HOME/.zeus}}

if [ -n "$(git status | grep -w 'working tree clean')" ]; then
    exit 0
fi

git add -A
git commit -m "Update at $(date "+%Y-%m-%d %T")" || true
git push origin master
